config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on=>:member
    end
  end

  root :to => 'store#index', :as => 'store'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
<%=@page_title ||t('.title') %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
      <div id="cart">
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
            <%= render @cart %>
          <% end %>
        <% end %>


      </div>
      <a href="/"><%= t('.home') %> </a> <br />
<a href="/faq">,<%= t('.questions') %> </a> <br />
<a href="/news">,<%= t('.news') %> </a> <br />
<a href="/contact">,<%= t('.contact') %> </a> <br />
      
	<%if session[:user_id]%>
	<br />
		<%= link_to 'orders', orders_path %><br />
		<%= link_to 'products', products_path %><br />
		<%= link_to 'users', users_path %><br />
     <br />
<%= button_to 'Logout', logout_path, :method=> :delete %>
<%end%>
    </div>
    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>
</body>
</html>